[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flet[all]>=0.25.1",
]

[project.scripts]
main = "app.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
